import * as esbuild from 'esbuild'
import { dirname, resolve } from "path";
import { fileURLToPath } from 'url';
    
const __dirname = dirname(fileURLToPath(import.meta.url));

const PAGES = [
    "BlogPostPage",
    "BulkUploadPage",
    "CubeSamplePackPage",
    "CubeAnalysisPage",
    "CubeBlogPage",
    "CubeComparePage",
    "CubeDeckPage",
    "CubeDecksPage",
    "CubeDeckbuilderPage",
    "CubeDraftPage",
    "CubeListPage",
    "CubeHistoryPage",
    "CubeOverviewPage",
    "CubePlaytestPage",
    "DashboardPage",
    "GridDraftPage",
    "DevBlog",
    "ContactPage",
    "DonatePage",
    "InfoPage",
    "FiltersPage",
    "DownTimePage",
    "ErrorPage",
    "CardSearchPage",
    "TopCardsPage",
    "CardPage",
    "CommentPage",
    "LoginPage",
    "RegisterPage",
    "LostPasswordPage",
    "NotificationsPage",
    "PasswordResetPage",
    "UserAccountPage",
    "UserBlogPage",
    "UserDecksPage",
    "UserSocialPage",
    "UserCubePage",
    "ExplorePage",
    "SearchPage",
    "RecentDraftsPage",
    "VersionPage",
    "LandingPage",
    "AdminDashboardPage",
    "NoticePage",
    "ApplicationPage",
    "CreatorsPage",
    "MarkdownPage",
    "EditArticlePage",
    "ArticlePage",
    "ReviewContentPage",
    "ArticlesPage",
    "EditVideoPage",
    "VideoPage",
    "VideosPage",
    "EditPodcastPage",
    "PodcastPage",
    "PodcastsPage",
    "PodcastEpisodePage",
    "BrowseContentPage",
    "LeaveWarningPage",
    "ApprovedPackagesPage",
    "SubmittedPackagesPage",
    "UserPackagesPage",
    "PackagePage",
    "FeaturedCubesQueuePage",
]

await esbuild.build({
  entryPoints: PAGES.map(page => ({out: page, in: `./src/pages/${page}.js`})),
  bundle: true,
  write: true,
  outdir: 'dist',
  nodePaths: [resolve(__dirname, "src"), resolve(__dirname, "node_modules")],
  loader: { '.js': 'jsx' },
})
