# Remember to override user agent to ELB-HealthChecker so that the app doesn't redirect to https in production mode
services:
  node:
    command:
      [
        'sh',
        '-c',
        'npm run nearley --watch & npm run nodemon & npm run webpack & npx tailwindcss -i ./src/client/css/stylesheet.css -o ./public/css/stylesheet.css --watch=always',
      ]
    environment:
      - NODE_ENV=production
      - LISTEN_ON=0.0.0.0
    ports: !override # Without webpack-dev-server, direct all traffic right to node
      - 8080:5000
    expose:
      - '8080'
      - '5000'
