/**
 * Application-specific error codes.
 * These codes can be used to identify specific error conditions in the application.
 */
export enum ErrorCode {
    // --- DAO ---
    OPTIMISTIC_LOCKING_VERSION_MISMATCH = "OPTIMISTIC_LOCKING_VERSION_MISMATCH",

    // --- Validation / Input ---
    VALIDATION_FAILED = "VALIDATION_FAILED",
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",

    // --- HTTP / Network / Resources ---
    BAD_REQUEST = "BAD_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
    CONFLICT = "CONFLICT",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

    // --- Misc / Other ---
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    FEATURE_NOT_IMPLEMENTED = "FEATURE_NOT_IMPLEMENTED",
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
    UNCAUGHT_EXCEPTION = "UNCAUGHT_EXCEPTION",
    UNHANDLED_REJECTION = "UNHANDLED_REJECTION",
}