export default {
  CYCLE: ['Canyon Slough', 'Fetid Pools', 'Irrigated Farmland', 'Scattered Groves', 'Sheltered Thicket'],

  BOUNCE: [
    'Azorius Chancery',
    'Boros Garrison',
    'Coral Atoll',
    'Dimir Aqueduct',
    'Dormant Volcano',
    'Everglades',
    'Golgari Rot Farm',
    'Gruul Turf',
    'Izzet Boilerworks',
    'Jungle Basin',
    'Karoo',
    'Orzhov Basilica',
    'Rakdos Carnarium',
    'Selesnya Sanctuary',
    'Simic Growth Chamber',
  ],

  CANOPY: [
    'Fiery Islet',
    'Horizon Canopy',
    'Nurturing Peatland',
    'Silent Clearing',
    'Sunbaked Canyon',
    'Waterlogged Grove',
  ],

  CHECK: [
    'Clifftop Retreat',
    'Dragonskull Summit',
    'Drowned Catacomb',
    'Glacial Fortress',
    'Hinterland Harbor',
    'Isolated Chapel',
    'Rootbound Crag',
    'Sulfur Falls',
    'Sunpetal Grove',
    'Woodland Cemetery',
  ],

  DUAL: [
    'Badlands',
    'Bayou',
    'Plateau',
    'Savannah',
    'Scrubland',
    'Taiga',
    'Tropical Island',
    'Tundra',
    'Underground Sea',
    'Volcanic Island',
  ],

  FAST: [
    'Blackcleave Cliffs',
    'Blooming Marsh',
    'Botanical Sanctum',
    'Concealed Courtyard',
    'Copperline Gorge',
    'Darkslick Shores',
    'Inspiring Vantage',
    'Razorverge Thicket',
    'Seachrome Coast',
    'Spirebluff Canal',
  ],

  FETCH: [
    'Arid Mesa',
    'Bloodstained Mire',
    'Flooded Strand',
    'Marsh Flats',
    'Misty Rainforest',
    'Polluted Delta',
    'Scalding Tarn',
    'Verdant Catacombs',
    'Windswept Heath',
    'Wooded Foothills',
  ],

  FILTER: [
    'Cascade Bluffs',
    'Cascading Cataracts',
    'Crystal Quarry',
    'Darkwater Catacombs',
    'Fetid Heath',
    'Fire-Lit Thicket',
    'Flooded Grove',
    'Graven Cairns',
    'Mossfire Valley',
    'Mystic Gate',
    'Rugged Prairie',
    'Shadowblood Ridge',
    'Skycloud Expanse',
    'Sungrass Prairie',
    'Sunken Ruins',
    'Twilight Mire',
    'Wooded Bastion',
  ],

  GAIN: [
    'Akoum Refuge',
    'Bloodfell Caves',
    'Blossoming Sands',
    'Dismal Backwater',
    'Graypelt Refuge',
    'Jungle Hollow',
    'Jwar Isle Refuge',
    'Kazandu Refuge',
    'Rugged Highlands',
    'Scoured Barrens',
    'Sejiri Refuge',
    'Swiftwater Cliffs',
    'Thornwood Falls',
    'Tranquil Cove',
    'Wind-Scarred Crag',
  ],

  PAIN: [
    'Adarkar Wastes',
    'Battlefield Forge',
    'Brushland',
    'Caves of Koilos',
    'Karplusan Forest',
    'Llanowar Wastes',
    'Shivan Reef',
    'Sulfurous Springs',
    'Underground River',
    'Yavimaya Coast',
  ],

  SCRY: [
    'Temple of Abandon',
    'Temple of Deceit',
    'Temple of Enlightenment',
    'Temple of Epiphany',
    'Temple of Malady',
    'Temple of Malice',
    'Temple of Mystery',
    'Temple of Plenty',
    'Temple of Silence',
    'Temple of Triumph',
  ],

  SHADOW: ['Choked Estuary', 'Foreboding Ruins', 'Fortified Village', 'Game Trail', 'Port Town'],

  SHOCK: [
    'Blood Crypt',
    'Breeding Pool',
    'Godless Shrine',
    'Hallowed Fountain',
    'Overgrown Tomb',
    'Sacred Foundry',
    'Steam Vents',
    'Stomping Ground',
    'Temple Garden',
    'Watery Grave',
  ],

  STORAGE: [
    'Bottomless Vault',
    'Calciform Pools',
    'Crucible of the Spirit Dragon',
    'Dreadship Reef',
    'Dwarven Hold',
    'Fungal Reaches',
    'Hollow Trees',
    'Icatian Store',
    'Mage-Ring Network',
    'Molten Slagheap',
    'Saltcrusted Steppe',
    'Sand Silos',
  ],

  TANGO: ['Canopy Vista', 'Cinder Glade', 'Prairie Stream', 'Smoldering Marsh', 'Sunken Hollow'],

  TRI: [
    'Arcane Sanctum',
    'Crumbling Necropolis',
    'Frontier Bivouac',
    'Jungle Shrine',
    'Mystic Monastery',
    'Nomad Outpost',
    'Opulent Palace',
    'Sandsteppe Citadel',
    'Savage Lands',
    'Seaside Citadel',
  ],
};
