import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';
import { defineConfig } from 'vite';

// Folder of source photos to annotate. Override with ANNOTATOR_IMAGES_DIR.
const IMAGES_DIR = process.env.ANNOTATOR_IMAGES_DIR
  ? path.resolve(process.env.ANNOTATOR_IMAGES_DIR)
  : path.resolve(__dirname, 'images');

// Where the per-image annotation JSON files are written.
const ANNOTATIONS_DIR = path.resolve(__dirname, 'data', 'annotations');

// Synthetic dataset (generated by scripts/generate-dataset.mjs): images plus
// their ground-truth label JSON, browsed read-only in the app's Synthetic mode.
const SYNTH_IMAGES_DIR = path.resolve(__dirname, 'data', 'synthetic', 'images');
const SYNTH_ANN_DIR = path.resolve(__dirname, 'data', 'synthetic', 'annotations');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp']);
const MIME: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.bmp': 'image/bmp',
};

const cleanName = (url: string): string => decodeURIComponent((url || '').split('?')[0].replace(/^\/+/, ''));

// Dev-server middleware that serves the local image folder and reads/writes
// annotation JSON — keeps everything to a single `vite` process, no separate API.
function annotatorApiPlugin() {
  return {
    name: 'annotator-api',
    configureServer(server: any) {
      fs.mkdirSync(ANNOTATIONS_DIR, { recursive: true });

      // List available images.
      server.middlewares.use('/api/images', (req: any, res: any, next: any) => {
        if (req.method !== 'GET') return next();
        let images: string[] = [];
        try {
          images = fs
            .readdirSync(IMAGES_DIR)
            .filter((f) => IMAGE_EXTS.has(path.extname(f).toLowerCase()))
            .sort();
        } catch {
          // images dir may not exist yet
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify({ images, dir: IMAGES_DIR }));
      });

      // The test set: real photos that have a hand annotation (the model's
      // held-out test split). Served via /img with ground truth at /api/annotations.
      server.middlewares.use('/api/test/images', (req: any, res: any, next: any) => {
        if (req.method !== 'GET') return next();
        let images: string[] = [];
        try {
          images = fs
            .readdirSync(ANNOTATIONS_DIR)
            .filter((f) => f.endsWith('.json'))
            .map((f) => f.slice(0, -'.json'.length))
            .filter((name) => fs.existsSync(path.join(IMAGES_DIR, name)))
            .sort();
        } catch {
          // annotations dir may be empty
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify({ images }));
      });

      // Serve an individual image.
      server.middlewares.use('/img', (req: any, res: any, next: any) => {
        if (req.method !== 'GET') return next();
        const filePath = path.join(IMAGES_DIR, cleanName(req.url));
        if (!filePath.startsWith(IMAGES_DIR) || !fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
          res.statusCode = 404;
          return res.end('Not found');
        }
        res.setHeader('Content-Type', MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream');
        fs.createReadStream(filePath).pipe(res);
      });

      // Read / write annotations for one image: /api/annotations/<imageName>.
      server.middlewares.use('/api/annotations', (req: any, res: any) => {
        const name = cleanName(req.url);
        const file = path.join(ANNOTATIONS_DIR, `${name}.json`);
        if (!file.startsWith(ANNOTATIONS_DIR)) {
          res.statusCode = 403;
          return res.end('Forbidden');
        }
        if (req.method === 'GET') {
          res.setHeader('Content-Type', 'application/json');
          if (fs.existsSync(file)) {
            fs.createReadStream(file).pipe(res);
          } else {
            res.end(JSON.stringify({ boxes: [] }));
          }
        } else if (req.method === 'POST') {
          let body = '';
          req.on('data', (chunk: any) => {
            body += chunk;
          });
          req.on('end', () => {
            try {
              JSON.parse(body); // validate
              fs.writeFileSync(file, body);
              res.setHeader('Content-Type', 'application/json');
              res.end(JSON.stringify({ ok: true }));
            } catch {
              res.statusCode = 400;
              res.end(JSON.stringify({ error: 'Invalid JSON' }));
            }
          });
        } else {
          res.statusCode = 405;
          res.end('Method not allowed');
        }
      });

      // ---- synthetic dataset (read-only viewer) ----------------------------

      // List generated synthetic images.
      server.middlewares.use('/api/synthetic/images', (req: any, res: any, next: any) => {
        if (req.method !== 'GET') return next();
        let images: string[] = [];
        try {
          images = fs
            .readdirSync(SYNTH_IMAGES_DIR)
            .filter((f) => IMAGE_EXTS.has(path.extname(f).toLowerCase()))
            .sort();
        } catch {
          // synthetic dir may not exist until the generator has been run
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify({ images, dir: SYNTH_IMAGES_DIR }));
      });

      // Ground-truth labels for one synthetic image.
      server.middlewares.use('/api/synthetic/annotations', (req: any, res: any) => {
        const name = cleanName(req.url);
        const file = path.join(SYNTH_ANN_DIR, `${name}.json`);
        if (!file.startsWith(SYNTH_ANN_DIR)) {
          res.statusCode = 403;
          return res.end('Forbidden');
        }
        res.setHeader('Content-Type', 'application/json');
        if (fs.existsSync(file)) fs.createReadStream(file).pipe(res);
        else res.end(JSON.stringify({ boxes: [] }));
      });

      // Serve a synthetic image.
      server.middlewares.use('/synthimg', (req: any, res: any, next: any) => {
        if (req.method !== 'GET') return next();
        const filePath = path.join(SYNTH_IMAGES_DIR, cleanName(req.url));
        if (!filePath.startsWith(SYNTH_IMAGES_DIR) || !fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
          res.statusCode = 404;
          return res.end('Not found');
        }
        res.setHeader('Content-Type', MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream');
        fs.createReadStream(filePath).pipe(res);
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), annotatorApiPlugin()],
  root: '.',
  server: {
    watch: {
      // Best-effort: don't watch the big unbundled trees. NOTE: this alone is not
      // enough on a low fs.inotify.max_user_watches (default 65536) when an IDE is
      // also watching this monorepo — Vite still recursively watches the root and
      // hits ENOSPC. The real fix is raising the system limit:
      //   echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/99-inotify.conf
      //   sudo sysctl --system
      ignored: [/(^|[\\/])(\.venv|images|data|training)([\\/]|$)/],
    },
  },
});
