/**
 * Maps Scryfall oracle tag names to canonical draft/cube archetype buckets.
 * Multiple raw tags (aliases, sub-tags, near-synonyms) consolidate into one bucket.
 * Noise tags (metadata, silver-border, DnD-specific, formatting oddities) are omitted.
 *
 * ~50 canonical buckets covering the most impactful draft/cube archetypes.
 */
export const OTAG_BUCKET_MAP: Record<string, string> = {
  // ── removal ──────────────────────────────────────────────────────────────
  removal: 'removal',
  'creature-removal': 'removal',
  'removal-creature': 'removal',
  'spot-removal': 'removal',
  'removal-burn': 'removal',
  'burn-creature': 'removal',
  'removal-creature-burn': 'removal',
  'planeswalker-removal': 'removal',
  'removal-planeswalker': 'removal',
  'removal-destroy': 'removal',
  'removal-exile': 'removal',
  'artifact-removal': 'removal',
  'removal-artifact': 'removal',
  'enchantment-removal': 'removal',
  'removal-enchantment': 'removal',
  'removal-aura': 'removal',
  'removal-equipment': 'removal',
  'removal-toughness': 'removal',
  'removal-nonland': 'removal',
  'removal-bounce': 'removal',
  'removal-fight': 'removal',
  'removal-creature-fight': 'removal',
  'removal-bite': 'removal',
  'removal-permanent': 'removal',
  'removal-sacrifice': 'removal',
  'removal-land': 'removal',
  'removal-battle': 'removal',
  'removal-battle-burn': 'removal',
  'removal-tuck': 'removal',
  'multi-removal': 'removal',
  edict: 'removal',
  'repeatable-removal': 'removal',
  'doom-blade': 'removal',
  bite: 'removal',
  'one-sided-fight': 'removal',

  // ── burn ─────────────────────────────────────────────────────────────────
  burn: 'burn',
  'burn-player': 'burn',
  'burn-any': 'burn',
  'burn-battle': 'burn',
  'burn-battle-burn': 'burn',
  pinger: 'burn',
  tim: 'burn',
  earthquake: 'burn',
  'damage-doubler': 'burn',
  'damage-multiplier': 'burn',
  'damage-tripler': 'burn',
  'burn-player-each': 'burn',
  'opponent-loses-life': 'burn',

  // ── card-advantage ────────────────────────────────────────────────────────
  'card-advantage': 'card-advantage',
  'draw-card': 'card-advantage',
  'pure-draw': 'card-advantage',
  'repeatable-draw': 'card-advantage',
  'draw-engine': 'card-advantage',
  'repeatable-pure-draw': 'card-advantage',
  cantrip: 'card-advantage',
  'burst-draw': 'card-advantage',
  impulse: 'card-advantage',
  'impulse-draw': 'card-advantage',
  'impulsive-draw': 'card-advantage',
  'bottle-draw': 'card-advantage',
  'repeatable-impulsive-draw': 'card-advantage',
  'life-for-cards': 'card-advantage',
  curiosity: 'card-advantage',
  'curiosity-like': 'card-advantage',
  'draw-matters': 'card-advantage',
  'second-draw-matters': 'card-advantage',
  tome: 'card-advantage',

  // ── evasion ───────────────────────────────────────────────────────────────
  evasion: 'evasion',
  'gives-evasion': 'evasion',
  'gives-flying': 'evasion',
  'gains-flying': 'evasion',
  'gives-haste': 'evasion',
  'gains-haste': 'evasion',
  'gives-trample': 'evasion',
  'gains-trample': 'evasion',
  'gives-unblockable': 'evasion',
  'gives-first-strike': 'evasion',
  'gains-first-strike': 'evasion',
  'gives-double-strike': 'evasion',
  'gains-double-strike': 'evasion',
  'gives-menace': 'evasion',
  'gains-menace': 'evasion',
  'gives-vigilance': 'evasion',
  'gains-vigilance': 'evasion',
  'gives-lifelink': 'evasion',
  'gains-lifelink': 'evasion',
  'gives-deathtouch': 'evasion',
  'gains-deathtouch': 'evasion',
  'gives-indestructible': 'evasion',
  'gains-indestructible': 'evasion',
  'gives-hexproof': 'evasion',
  'gains-hexproof': 'evasion',
  'gives-reach': 'evasion',
  'gives-ward': 'evasion',
  'gives-skulk': 'evasion',
  unblockable: 'evasion',
  saboteur: 'evasion',
  'unique-evasion': 'evasion',

  // ── ramp ──────────────────────────────────────────────────────────────────
  acceleration: 'ramp',
  'mana-ramp': 'ramp',
  ramp: 'ramp',
  'mana-producer': 'ramp',
  'mana-dork': 'ramp',
  'mana-rock': 'ramp',
  manarock: 'ramp',
  'manarock-any-color': 'ramp',
  'manarock-c': 'ramp',
  'manarock-cc': 'ramp',
  'manarock-ccc': 'ramp',
  'manarock-chosen-color': 'ramp',
  'adds-multiple-mana': 'ramp',
  'produces-multiple-mana': 'ramp',
  'tutor-land': 'ramp',
  'tutor-land-basic': 'ramp',
  'tutor-land-to-battlefield': 'ramp',
  'extra-land': 'ramp',
  'wild-growth': 'ramp',
  'mana-doubler': 'ramp',
  'mana-flare': 'ramp',
  'mana-increaser': 'ramp',
  'ramp-with-set-mechanic': 'ramp',
  'ramp-with-sets-mechanic': 'ramp',
  'utility-mana-rock': 'ramp',
  'mana-rock-with-sets-mechanic': 'ramp',
  fixing: 'ramp',
  'mana-fix': 'ramp',

  // ── landfall ──────────────────────────────────────────────────────────────
  landfall: 'landfall',
  'lands-matter': 'landfall',
  'synergy-land': 'landfall',

  // ── mana-sink ─────────────────────────────────────────────────────────────
  'mana-dump': 'mana-sink',
  'mana-sink': 'mana-sink',
  'bottomless-mana-sink': 'mana-sink',
  'infinite-mana-sink': 'mana-sink',
  firebreathing: 'mana-sink',
  'shade-pump': 'mana-sink',

  // ── tribal ────────────────────────────────────────────────────────────────
  kindred: 'tribal',
  tribal: 'tribal',
  typal: 'tribal',
  'typal-creature': 'tribal',
  'tribal-coupling': 'tribal',
  'typal-coupling': 'tribal',
  anthem: 'tribal',
  lord: 'tribal',
  'keyword-anthem': 'tribal',
  'tribal-dragon': 'tribal',
  'typal-dragon': 'tribal',
  'dragon-tribal': 'tribal',
  'tribal-elf': 'tribal',
  'typal-elf': 'tribal',
  'tribal-goblin': 'tribal',
  'typal-goblin': 'tribal',
  'goblin-synergy': 'tribal',
  'tribal-zombie': 'tribal',
  'typal-zombie': 'tribal',
  'zombie-lord': 'tribal',
  'tribal-sliver': 'tribal',
  'typal-sliver': 'tribal',
  'tribal-vampire': 'tribal',
  'typal-vampire': 'tribal',
  'vampire-lord': 'tribal',
  'tribal-warrior': 'tribal',
  'typal-warrior': 'tribal',
  'tribal-wizard': 'tribal',
  'typal-wizard': 'tribal',
  'tribal-spirit': 'tribal',
  'typal-spirit': 'tribal',
  'spirit-lord': 'tribal',
  'tribal-merfolk': 'tribal',
  'typal-merfolk': 'tribal',
  'tribal-rogue': 'tribal',
  'typal-rogue': 'tribal',
  'tribal-human': 'tribal',
  'typal-human': 'tribal',
  'human-tribal': 'tribal',
  'tribal-ally': 'tribal',
  'typal-ally': 'tribal',
  'tribal-cleric': 'tribal',
  'typal-cleric': 'tribal',
  'tribal-pirate': 'tribal',
  'typal-pirate': 'tribal',
  'tribal-knight': 'tribal',
  'typal-knight': 'tribal',
  'tribal-soldier': 'tribal',
  'typal-soldier': 'tribal',
  'tribal-assassin': 'tribal',
  'typal-assassin': 'tribal',
  'tribal-dinosaur': 'tribal',
  'typal-dinosaur': 'tribal',
  'tribal-army': 'tribal',
  'typal-army': 'tribal',
  'tribal-choose': 'tribal',
  'typal-choose': 'tribal',
  'black-lord': 'tribal',
  'lord-black': 'tribal',
  changeling: 'tribal',
  'hate-typal': 'tribal',
  'tribal-hate': 'tribal',
  'synergy-spirit': 'tribal',
  'synergy-knight': 'tribal',
  'synergy-party': 'tribal',

  // ── lifegain ──────────────────────────────────────────────────────────────
  'life-gain': 'lifegain',
  lifegain: 'lifegain',
  'repeatable-lifegain': 'lifegain',
  'lifegain-matters': 'lifegain',
  'synergy-lifegain': 'lifegain',
  'life-payment': 'lifegain',
  'life-total-matters-self': 'lifegain',
  'opponent-lifegain': 'lifegain',
  'drain-life': 'lifegain',
  'life-drain': 'lifegain',
  'drain-creature': 'lifegain',

  // ── recursion ─────────────────────────────────────────────────────────────
  recursion: 'recursion',
  'recursion-creature': 'recursion',
  reanimate: 'recursion',
  resurrect: 'recursion',
  zombify: 'recursion',
  'reanimate-cast': 'recursion',
  'reanimate-from-any': 'recursion',
  'reanimate-from-opponent': 'recursion',
  'reanimate-permanent': 'recursion',
  'reanimate-copy': 'recursion',
  'reanimate-land': 'recursion',
  'reanimate-artifact': 'recursion',
  recall: 'recursion',
  regrowth: 'recursion',
  'regrowth-creature': 'recursion',
  'regrowth-instant': 'recursion',
  'regrowth-sorcery': 'recursion',
  'regrowth-artifact': 'recursion',
  'regrowth-planeswalker': 'recursion',
  'regrowth-permanent': 'recursion',
  'regrowth-any': 'recursion',
  'regrowth-self': 'recursion',
  'self-recall': 'recursion',
  'self-regrowth': 'recursion',
  'recursion-self': 'recursion',
  'reanimate-self': 'recursion',
  'self-reanimate': 'recursion',
  'recursion-permanent': 'recursion',
  'recursion-enchantment': 'recursion',
  'recursion-instant': 'recursion',
  'recursion-sorcery': 'recursion',
  'recursion-artifact': 'recursion',
  'recursion-planeswalker': 'recursion',
  'recursion-any': 'recursion',
  'recursion-land': 'recursion',
  restock: 'recursion',
  'restock-self': 'recursion',
  'self-restock': 'recursion',
  'restock-to-top': 'recursion',
  rescue: 'recursion',
  'rescue-creature': 'recursion',
  'rescue-enchantment': 'recursion',
  'rescue-artifact': 'recursion',
  'rescue-land': 'recursion',
  'mass-reanimation': 'recursion',
  unexile: 'recursion',
  'castable-from-graveyard': 'recursion',
  flashback: 'recursion',
  'cast-from-graveyard': 'recursion',
  'activate-from-graveyard': 'recursion',
  'cast-from-nonhand': 'recursion',
  'gives-castable-from-nonhand': 'recursion',
  'castable-from-nonhand': 'recursion',
  'cheat-death': 'recursion',
  'cheat-death-self': 'recursion',
  'creature-reanimation-automatic': 'recursion',
  graveflicker: 'recursion',
  'temporary-reanimation': 'recursion',
  'trigger-from-graveyard': 'recursion',
  'cast-on-resolution': 'recursion',
  'homeward-effect': 'recursion',

  // ── graveyard-matters ─────────────────────────────────────────────────────
  'graveyard-fuel': 'graveyard-matters',
  'cards-in-graveyard-matter': 'graveyard-matters',
  'graveyard-fuel-creature': 'graveyard-matters',
  'graveyard-fuel-self': 'graveyard-matters',
  threshold: 'graveyard-matters',
  hellbent: 'graveyard-matters',
  undergrowth: 'graveyard-matters',
  'card-types-in-graveyard-matter': 'graveyard-matters',
  'synergy-graveyard-cast': 'graveyard-matters',

  // ── looting ───────────────────────────────────────────────────────────────
  loot: 'looting',
  rummage: 'looting',
  'repeatable-loot': 'looting',
  'repeatable-rummage': 'looting',
  'discard-outlet': 'looting',
  discardoutlet: 'looting',
  discard: 'looting',
  'discard-outlet-land': 'looting',
  'discard-exile': 'looting',
  'discard-to-exile': 'looting',

  // ── mill ──────────────────────────────────────────────────────────────────
  mill: 'mill',
  'mill-opponent': 'mill',
  'mill-any': 'mill',
  'mill-each': 'mill',
  'mill-exile': 'mill',
  'mill-self': 'mill',
  'self-mill': 'mill',
  'deck-destruction': 'mill',
  'synergy-mill': 'mill',
  'graveyard-seal': 'mill',

  // ── counterspells ─────────────────────────────────────────────────────────
  counter: 'counterspells',
  counterspell: 'counterspells',
  'counterspell-soft': 'counterspells',
  'soft-counter': 'counterspells',
  'counterspell-reusable': 'counterspells',
  'counterspell-ability': 'counterspells',
  'counterspell-creature': 'counterspells',
  stifle: 'counterspells',
  'counter-fuel': 'counterspells',
  'counterspell-with-set-mechanic': 'counterspells',
  'counterspell-with-sets-mechanic': 'counterspells',

  // ── +1/+1-counters ────────────────────────────────────────────────────────
  'counters-matter': '+1/+1-counters',
  'power-boost-to-all': '+1/+1-counters',
  'toughness-boost-to-all': '+1/+1-counters',
  'power-matters': '+1/+1-counters',
  'power-matters-self': '+1/+1-counters',
  'power-matters-individual': '+1/+1-counters',
  'gives-1-1-counters-to-all': '+1/+1-counters',
  'gives-counters-to-all': '+1/+1-counters',
  'giant-growth': '+1/+1-counters',
  'giant-growth-with-set-mechanic': '+1/+1-counters',
  'giant-growth-with-sets-mechanic': '+1/+1-counters',
  enlarge: '+1/+1-counters',
  'scales-with-power': '+1/+1-counters',
  'toughness-matters': '+1/+1-counters',
  'counter-increaser': '+1/+1-counters',
  'counter-doubler': '+1/+1-counters',
  'counter-movement': '+1/+1-counters',
  'move-counters': '+1/+1-counters',
  'ability-counter': '+1/+1-counters',
  'keyword-counter': '+1/+1-counters',
  'scales-with-multiple': '+1/+1-counters',
  'remove-counters': '+1/+1-counters',
  'remove-counters-you': '+1/+1-counters',

  // ── blink-flicker ─────────────────────────────────────────────────────────
  blink: 'blink-flicker',
  flicker: 'blink-flicker',
  'flicker-creature': 'blink-flicker',
  'flicker-slow': 'blink-flicker',
  'blink-slow': 'blink-flicker',
  'enters-in-company': 'blink-flicker',
  'etb-other-creature': 'blink-flicker',
  alliance: 'blink-flicker',
  creaturefall: 'blink-flicker',
  'leaves-battlefield-trigger': 'blink-flicker',
  'leaves-trigger-self': 'blink-flicker',

  // ── copy ──────────────────────────────────────────────────────────────────
  copy: 'copy',
  'copy-creature': 'copy',
  'copy-self': 'copy',
  'copy-spell': 'copy',
  'copy-instant': 'copy',
  'copy-sorcery': 'copy',
  'copy-artifact': 'copy',
  'copy-from-graveyard': 'copy',
  clone: 'copy',
  'animate-self': 'copy',
  'becomes-creature': 'copy',

  // ── tutor ─────────────────────────────────────────────────────────────────
  tutor: 'tutor',
  'tutor-to': 'tutor',
  'tutor-hand': 'tutor',
  'tutor-to-hand': 'tutor',
  'tutor-battlefield': 'tutor',
  'tutor-onto-battlefield': 'tutor',
  'tutor-to-battlefield': 'tutor',
  'tutor-creature': 'tutor',
  'tutor-artifact': 'tutor',
  'tutor-any': 'tutor',
  'tutor-card': 'tutor',
  'tutor-mv': 'tutor',
  'tutor-cmc': 'tutor',
  'tutor-seek': 'tutor',
  'tutor-to-top': 'tutor',
  'tutor-totop': 'tutor',
  'demonic-tutor': 'tutor',
  consult: 'tutor',
  'consult-cast': 'tutor',
  'consult-onto-battlefield': 'tutor',
  seek: 'tutor',
  'seek-to-hand': 'tutor',
  wish: 'tutor',

  // ── cheat-mana ────────────────────────────────────────────────────────────
  'cheat-mana': 'cheat-mana',
  'cost-ignorer': 'cheat-mana',
  'free-casting': 'cheat-mana',
  'cheat-into-play': 'cheat-mana',
  sneak: 'cheat-mana',
  'sneak-creature': 'cheat-mana',
  'sneak-from-library': 'cheat-mana',
  'sneak-self': 'cheat-mana',
  'sneak-land': 'cheat-mana',
  'cast-from-library': 'cheat-mana',
  'gives-castable-from-library': 'cheat-mana',
  'cast-from-top': 'cheat-mana',
  'play-from-top': 'cheat-mana',
  'cost-reducer': 'cheat-mana',
  'cost-reducer-self': 'cheat-mana',
  'discount-self': 'cheat-mana',
  'cheaper-than-mv': 'cheat-mana',
  'less-expensive-than-mv': 'cheat-mana',
  convoke: 'cheat-mana',
  affinity: 'cheat-mana',
  'potentially-free': 'cheat-mana',
  'phyrexian-mana': 'cheat-mana',
  'offcolor-kicker': 'cheat-mana',
  'offcolor-additional-cost': 'cheat-mana',
  'free-cast-another': 'cheat-mana',
  'alternate-cost-tap-creature': 'cheat-mana',
  'discount-tap-creature': 'cheat-mana',
  'alternate-cost-sacrifice': 'cheat-mana',

  // ── hand-disruption ───────────────────────────────────────────────────────
  'hand-disruption': 'hand-disruption',
  coercion: 'hand-disruption',
  duress: 'hand-disruption',
  thoughtseize: 'hand-disruption',
  'hand-size-matters': 'hand-disruption',
  handsize: 'hand-disruption',
  'high-hand-size-matters': 'hand-disruption',
  'low-hand-size-matters': 'hand-disruption',
  'hand-size-hate': 'hand-disruption',
  'hand-size-increase': 'hand-disruption',
  'discard-with-sets-mechanic': 'hand-disruption',

  // ── library-manipulation ──────────────────────────────────────────────────
  'library-manipulation': 'library-manipulation',
  'top-deck-manipulation': 'library-manipulation',
  'bottom-deck-manipulation': 'library-manipulation',
  scry: 'library-manipulation',
  surveil: 'library-manipulation',
  peek: 'library-manipulation',
  'peek-hand': 'library-manipulation',
  'peek-library': 'library-manipulation',
  'spy-library': 'library-manipulation',
  'impulse-to-zone': 'library-manipulation',
  'impulse-onto-battlefield': 'library-manipulation',
  'impulse-artifact': 'library-manipulation',
  'impulse-land': 'library-manipulation',
  'impulse-creature': 'library-manipulation',

  // ── bounce ────────────────────────────────────────────────────────────────
  bounce: 'bounce',
  'bounce-self': 'bounce',
  'man-o-war': 'bounce',
  tuck: 'bounce',
  'tuck-self': 'bounce',

  // ── sweeper ───────────────────────────────────────────────────────────────
  boardwipe: 'sweeper',
  'mass-removal': 'sweeper',
  sweeper: 'sweeper',
  wipe: 'sweeper',
  'wrath-of-god': 'sweeper',
  'sweeper-one-sided': 'sweeper',
  'sweeper-graveyard': 'sweeper',

  // ── protection ────────────────────────────────────────────────────────────
  'protects-creature': 'protection',
  'combat-trick': 'protection',
  'damage-prevention': 'protection',
  'prevent-damage': 'protection',
  'damage-prevention-creature': 'protection',
  'damage-prevention-you': 'protection',
  'damage-prevention-self': 'protection',
  fog: 'protection',
  'fog-limited': 'protection',
  'fog-selective': 'protection',
  'pseudo-fog': 'protection',
  'regenerates-self': 'protection',
  'regenerates-other': 'protection',
  'gives-protection': 'protection',
  'protects-artifact': 'protection',
  'protects-planeswalker': 'protection',
  'protects-land': 'protection',
  freeze: 'protection',
  stun: 'protection',
  'freeze-creature': 'protection',
  'stun-creature': 'protection',
  lockdown: 'protection',
  'lockdown-creature': 'protection',
  arrest: 'protection',
  pacifism: 'protection',

  // ── theft ─────────────────────────────────────────────────────────────────
  theft: 'theft',
  'theft-creature': 'theft',
  'theft-cast': 'theft',
  'theft-artifact': 'theft',
  'theft-threaten': 'theft',
  threaten: 'theft',
  'control-changing-effects': 'theft',
  donate: 'theft',
  defector: 'theft',
  'regain-control': 'theft',

  // ── token-generation ──────────────────────────────────────────────────────
  'repeatable-token-generator': 'token-generation',
  'repeatable-creature-tokens': 'token-generation',
  'multiple-bodies': 'token-generation',
  'token-versions-of-cards': 'token-generation',
  'repeatable-artifact-tokens': 'token-generation',
  'out-of-color-token': 'token-generation',
  'temporary-token': 'token-generation',
  'copy-token': 'token-generation',
  'named-token': 'token-generation',
  'donate-token': 'token-generation',
  'splits-on-death': 'token-generation',
  'doomed-traveler': 'token-generation',
  'leaves-body-behind': 'token-generation',
  'repeatable-noncreature-tokens': 'token-generation',
  'synergy-token': 'token-generation',
  'synergy-token-creature': 'token-generation',

  // ── sacrifice ─────────────────────────────────────────────────────────────
  'sac-outlet': 'sacrifice',
  'sacrifice-outlet': 'sacrifice',
  'sacrifice-outlet-creature': 'sacrifice',
  'sacrifice-outlet-artifact': 'sacrifice',
  'sacrifice-outlet-enchantment': 'sacrifice',
  'sacrifice-outlet-land': 'sacrifice',
  'sacrifice-outlet-permanent': 'sacrifice',
  'sacrifice-self': 'sacrifice',
  'free-sac-outlet': 'sacrifice',
  'free-sacrifice-outlet': 'sacrifice',
  'repeatable-sacrifice-outlet': 'sacrifice',
  'death-trigger': 'sacrifice',
  deathtrigger: 'sacrifice',
  'death-trigger-self': 'sacrifice',
  morbid: 'sacrifice',
  'synergy-sacrifice': 'sacrifice',
  martyr: 'sacrifice',
  egg: 'sacrifice',

  // ── attack-triggers ───────────────────────────────────────────────────────
  'attack-trigger': 'attack-triggers',
  'attacking-matters-self': 'attack-triggers',
  'attacking-matters': 'attack-triggers',
  'block-trigger': 'attack-triggers',
  'cast-trigger': 'attack-triggers',
  'cast-trigger-you': 'attack-triggers',
  'cast-trigger-other': 'attack-triggers',
  'cast-trigger-self': 'attack-triggers',
  'titan-trigger': 'attack-triggers',

  // ── hate ──────────────────────────────────────────────────────────────────
  hate: 'hate',
  'hate-artifact': 'hate',
  'graveyard-hate': 'hate',
  'hate-graveyard': 'hate',
  'hate-blocker': 'hate',
  'hate-attacker': 'hate',
  'hate-discard': 'hate',
  'hate-counterspell': 'hate',
  'hate-draw': 'hate',
  'draw-hate': 'hate',
  'hate-enchantment': 'hate',
  'hate-nonbasic-land': 'hate',
  'hate-planeswalker': 'hate',
  'hate-flying': 'hate',
  'flying-hate': 'hate',
  'hate-tapped': 'hate',
  'hate-set-mechanic': 'hate',
  'hate-instant': 'hate',
  'hate-sorcery': 'hate',
  'hate-target': 'hate',
  'hate-high-pt': 'hate',
  'hate-low-power': 'hate',
  'hate-full-hand': 'hate',
  'hate-regenerate': 'hate',
  'hate-regeneration': 'hate',
  'prevent-regeneration': 'hate',
  'stops-regeneration': 'hate',
  'hate-white': 'hate',
  'white-hate': 'hate',
  'hate-black': 'hate',
  'black-hate': 'hate',
  'hate-red': 'hate',
  'red-hate': 'hate',
  'hate-green': 'hate',
  'green-hate': 'hate',
  'hate-blue': 'hate',
  'blue-hate': 'hate',
  hatebear: 'hate',
  'hate-color': 'hate',
  'hate-color-choose': 'hate',
  'color-hate': 'hate',

  // ── land-matters ──────────────────────────────────────────────────────────
  'utility-land': 'land-matters',
  'cycle-land': 'land-matters',
  'cycle-dual-land': 'land-matters',
  'dual-land': 'land-matters',
  tapland: 'land-matters',
  'tapland-with-set-mechanic': 'land-matters',
  'tapland-with-sets-mechanic': 'land-matters',
  fetchland: 'land-matters',
  filterland: 'land-matters',
  painland: 'land-matters',
  'rainbow-land': 'land-matters',
  'cycle-mono-land': 'land-matters',
  creatureland: 'land-matters',
  'man-land': 'land-matters',
  manland: 'land-matters',
  'land-removal': 'land-matters',
  'land-sacrifice': 'land-matters',
  'land-conversion': 'land-matters',
  'mass-land-denial': 'land-matters',
  'animate-land': 'land-matters',
  'untap-land': 'land-matters',
  'untapper-land': 'land-matters',
  'conditional-tapland': 'land-matters',
  'etb-self-tapped-conditional': 'land-matters',
  'nonbasic-basic-land-type': 'land-matters',

  // ── artifact-synergy ──────────────────────────────────────────────────────
  'synergy-artifact': 'artifact-synergy',
  'synergy-artifact-creature': 'artifact-synergy',
  artifactfall: 'artifact-synergy',
  'becomes-artifact': 'artifact-synergy',
  artifactify: 'artifact-synergy',
  'tap-artifact': 'artifact-synergy',
  'tapper-artifact': 'artifact-synergy',
  'tap-fuel-artifact': 'artifact-synergy',
  'untapper-artifact': 'artifact-synergy',
  'mana-storage': 'artifact-synergy',
  'living-weapon': 'artifact-synergy',
  'synergy-equipment': 'artifact-synergy',
  'animate-artifact': 'artifact-synergy',
  'auto-equip': 'artifact-synergy',
  'quick-attach': 'artifact-synergy',
  'quick-equip': 'artifact-synergy',
  'snap-on': 'artifact-synergy',
  'etb-self-attach': 'artifact-synergy',

  // ── enchantment-synergy ───────────────────────────────────────────────────
  'synergy-enchantment': 'enchantment-synergy',
  enchantmentfall: 'enchantment-synergy',
  constellation: 'enchantment-synergy',
  'synergy-aura': 'enchantment-synergy',
  disenchant: 'enchantment-synergy',
  'disenchant-naturalize': 'enchantment-synergy',
  naturalize: 'enchantment-synergy',
  'synergy-saga': 'enchantment-synergy',

  // ── tapping ───────────────────────────────────────────────────────────────
  tapper: 'tapping',
  'tap-creature': 'tapping',
  'tapper-creature': 'tapping',
  'tap-outlet': 'tapping',
  'tap-fuel-creature': 'tapping',
  'tapper-land': 'tapping',
  'tapper-planeswalker': 'tapping',
  'tapper-permanent': 'tapping',
  untapper: 'tapping',
  'untapper-creature': 'tapping',
  'untap-creature': 'tapping',
  'untapper-self': 'tapping',
  'untaps-self': 'tapping',
  'untapper-permanent': 'tapping',
  'untapper-nonland': 'tapping',
  'gives-tap-ability': 'tapping',
  twiddle: 'tapping',

  // ── extra-turns ───────────────────────────────────────────────────────────
  'extra-turn': 'extra-turns',
  'extra-attack': 'extra-turns',
  'extra-combat': 'extra-turns',
  'extra-combat-phase': 'extra-turns',

  // ── spells-matter ─────────────────────────────────────────────────────────
  'synergy-instant': 'spells-matter',
  'synergy-sorcery': 'spells-matter',
  'synergy-noncreature': 'spells-matter',
  'second-spell-matters': 'spells-matter',
  heroic: 'spells-matter',
  strive: 'spells-matter',

  // ── mana-value-matters ────────────────────────────────────────────────────
  'mana-value-matters': 'mana-value-matters',
  'cmc-matters': 'mana-value-matters',
  'converted-mana-cost-matters': 'mana-value-matters',
  'bigger-than-mv': 'mana-value-matters',
  'more-expensive-than-mv': 'mana-value-matters',
  lhurgoyf: 'mana-value-matters',

  // ── group-slug ────────────────────────────────────────────────────────────
  'group-slug': 'group-slug',
  punisher: 'group-slug',
  'villainous-choice': 'group-slug',
  rhystic: 'group-slug',
  tax: 'group-slug',
  'cost-increaser': 'group-slug',
  toll: 'group-slug',
  'per-opponent': 'group-slug',
  'per-player': 'group-slug',
  dilemma: 'group-slug',
  'opponent-chooses': 'group-slug',

  // ── group-hug ─────────────────────────────────────────────────────────────
  'group-hug': 'group-hug',
  'selective-group-hug': 'group-hug',
  symmetrical: 'group-hug',

  // ── combat-tricks ─────────────────────────────────────────────────────────
  'combat-manipulation': 'combat-tricks',
  'combat-mana': 'combat-tricks',
  'combat-ramp': 'combat-tricks',
  'combat-neutral-damage-trigger': 'combat-tricks',
  'force-attacker': 'combat-tricks',
  'forces-attack': 'combat-tricks',
  'forced-attacker': 'combat-tricks',
  'force-blocker': 'combat-tricks',
  'prevent-attack': 'combat-tricks',
  'prevent-attacker': 'combat-tricks',
  'restricted-blocker': 'combat-tricks',
  'restricted-attacker': 'combat-tricks',

  // ── overrun ───────────────────────────────────────────────────────────────
  overrun: 'overrun',

  // ── modal ─────────────────────────────────────────────────────────────────
  modal: 'modal',
  charm: 'modal',
  'beast-within': 'modal',
  pongify: 'modal',

  // ── pillowfort ────────────────────────────────────────────────────────────
  pillowfort: 'pillowfort',
  'damage-deflection': 'pillowfort',
  'damage-redirection': 'pillowfort',
  'redirect-damage': 'pillowfort',

  // ── alternate-win ─────────────────────────────────────────────────────────
  'alternate-win-condition': 'alternate-win',
  'automatic-win': 'alternate-win',
  'win-condition': 'alternate-win',
  exponential: 'alternate-win',
  quadratic: 'alternate-win',

  // ── poison ────────────────────────────────────────────────────────────────
  'poison-mechanics': 'poison',
  poisonous: 'poison',
  'gives-mm-counters': 'poison',
  'mm-counters-matter': 'poison',

  // ── planeswalker-support ──────────────────────────────────────────────────
  'planeswalker-support': 'planeswalker-support',
  'synergy-planeswalker': 'planeswalker-support',

  // ── energy ────────────────────────────────────────────────────────────────
  'energy-generator': 'energy',
  'counter-fuel-energy': 'energy',

  // ── legendary-matters ─────────────────────────────────────────────────────
  'synergy-legendary': 'legendary-matters',

  // ── food-treasure ─────────────────────────────────────────────────────────
  'repeatable-food': 'food-treasure',
  'repeatable-treasures': 'food-treasure',
  'synergy-treasure': 'food-treasure',
  'repeatable-clues': 'food-treasure',
  'synergy-food': 'food-treasure',

  // ── colorless-matters ─────────────────────────────────────────────────────
  'synergy-colorless': 'colorless-matters',
  'colourless-matters': 'colorless-matters',

  // ── snow-matters ──────────────────────────────────────────────────────────
  'synergy-snow': 'snow-matters',

  // ── multicolor-matters ────────────────────────────────────────────────────
  'synergy-multicolor': 'multicolor-matters',
  'synergy-color-multi': 'multicolor-matters',
  'synergy-color-each': 'multicolor-matters',
  'synergy-color-share': 'multicolor-matters',

  // ── historic ──────────────────────────────────────────────────────────────
  'synergy-historic': 'historic',

  // ── color-matters ─────────────────────────────────────────────────────────
  'color-spent-matters': 'color-matters',
  'mana-spent-matters': 'color-matters',
  'offcolor-ability': 'color-matters',
  'color-change': 'color-matters',
  'color-change-self': 'color-matters',
  ferocious: 'color-matters',

  // ── discard-payoff ────────────────────────────────────────────────────────
  'discard-matters': 'discard-payoff',
  'synergy-discard': 'discard-payoff',
  'synergy-discard-self': 'discard-payoff',
  'self-discard-matters': 'discard-payoff',
  madness: 'discard-payoff',

  // ── instant-speed ─────────────────────────────────────────────────────────
  'gives-flash': 'instant-speed',
  'instant-rebate': 'instant-speed',
  refund: 'instant-speed',
  'full-refund': 'instant-speed',
  'mini-refund': 'instant-speed',

  // (draw-matters, second-draw-matters, curiosity-like already mapped to card-advantage above)

  // ── cast-from-exile ───────────────────────────────────────────────────────
  'cast-from-exile': 'cast-from-exile',
  'gives-castable-from-exile': 'cast-from-exile',
  'castable-from-exile': 'cast-from-exile',
  // cast-from-nonhand / gives-castable-from-nonhand already mapped to recursion above

  // ── graveyard-hate ────────────────────────────────────────────────────────
  'exile-self': 'graveyard-hate',
  'exiles-self': 'graveyard-hate',
  'graveyard-to-library': 'graveyard-hate',
  // sweeper-graveyard already mapped to sweeper above
};
