/**
 * Conservative OTAG -> archetype bucket mapping.
 *
 * Philosophy:
 * - bias toward precision over recall
 * - only map tags that feel like real deck labels
 * - avoid generic gameplay descriptors that create noisy deck names
 * - prefer under-tagging to over-tagging
 */
export const OTAG_BUCKET_MAP: Record<string, string> = {
  // ── removal ──────────────────────────────────────────────────────────────
  removal: 'removal',
  'creature-removal': 'removal',
  'removal-creature': 'removal',
  'spot-removal': 'removal',
  'removal-burn': 'removal',
  'burn-creature': 'removal',
  'removal-creature-burn': 'removal',
  'planeswalker-removal': 'removal',
  'removal-planeswalker': 'removal',
  'removal-destroy': 'removal',
  'removal-exile': 'removal',
  'artifact-removal': 'removal',
  'removal-artifact': 'removal',
  'enchantment-removal': 'removal',
  'removal-enchantment': 'removal',
  'removal-aura': 'removal',
  'removal-equipment': 'removal',
  'removal-toughness': 'removal',
  'removal-nonland': 'removal',
  'removal-bounce': 'removal',
  'removal-fight': 'removal',
  'removal-creature-fight': 'removal',
  'removal-bite': 'removal',
  'removal-permanent': 'removal',
  'removal-sacrifice': 'removal',
  'removal-land': 'removal',
  'removal-battle': 'removal',
  'removal-battle-burn': 'removal',
  'removal-tuck': 'removal',
  'multi-removal': 'removal',
  edict: 'removal',
  'repeatable-removal': 'removal',
  'doom-blade': 'removal',
  bite: 'removal',
  'one-sided-fight': 'removal',
  arrest: 'removal',
  pacifism: 'removal',

  // ── burn ─────────────────────────────────────────────────────────────────
  burn: 'burn',
  'burn-player': 'burn',
  'burn-any': 'burn',
  'burn-battle': 'burn',
  'burn-battle-burn': 'burn',
  pinger: 'burn',
  tim: 'burn',
  earthquake: 'burn',
  'damage-doubler': 'burn',
  'damage-multiplier': 'burn',
  'damage-tripler': 'burn',
  'burn-player-each': 'burn',
  'opponent-loses-life': 'burn',

  // ── card advantage ───────────────────────────────────────────────────────
  'card-advantage': 'draw / card-advantage',
  'draw-card': 'draw / card-advantage',
  'pure-draw': 'draw / card-advantage',
  'repeatable-draw': 'draw / card-advantage',
  'draw-engine': 'draw / card-advantage',
  'repeatable-pure-draw': 'draw / card-advantage',
  cantrip: 'draw / card-advantage',
  'burst-draw': 'draw / card-advantage',
  impulse: 'draw / card-advantage',
  'impulse-draw': 'draw / card-advantage',
  'impulsive-draw': 'draw / card-advantage',
  'bottle-draw': 'draw / card-advantage',
  'repeatable-impulsive-draw': 'draw / card-advantage',
  'life-for-cards': 'draw / card-advantage',
  curiosity: 'draw / card-advantage',
  'curiosity-like': 'draw / card-advantage',
  'draw-matters': 'draw / card-advantage',
  'second-draw-matters': 'draw / card-advantage',
  tome: 'draw / card-advantage',

  // ── evasion ──────────────────────────────────────────────────────────────
  evasion: 'evasion',
  'gives-evasion': 'evasion',
  'gives-flying': 'evasion',
  'gains-flying': 'evasion',
  'gives-unblockable': 'evasion',
  'gives-menace': 'evasion',
  'gains-menace': 'evasion',
  'gives-skulk': 'evasion',
  unblockable: 'evasion',
  saboteur: 'evasion',
  'unique-evasion': 'evasion',

  // ── ramp ─────────────────────────────────────────────────────────────────
  acceleration: 'ramp',
  'mana-ramp': 'ramp',
  ramp: 'ramp',
  'mana-producer': 'ramp',
  'mana-dork': 'ramp',
  'mana-rock': 'ramp',
  manarock: 'ramp',
  'manarock-any-color': 'ramp',
  'manarock-c': 'ramp',
  'manarock-cc': 'ramp',
  'manarock-ccc': 'ramp',
  'manarock-chosen-color': 'ramp',
  'adds-multiple-mana': 'ramp',
  'produces-multiple-mana': 'ramp',
  'tutor-land': 'ramp',
  'tutor-land-basic': 'ramp',
  'tutor-land-to-battlefield': 'ramp',
  'extra-land': 'ramp',
  'wild-growth': 'ramp',
  'mana-doubler': 'ramp',
  'mana-flare': 'ramp',
  'mana-increaser': 'ramp',
  'ramp-with-set-mechanic': 'ramp',
  'ramp-with-sets-mechanic': 'ramp',
  'utility-mana-rock': 'ramp',
  'mana-rock-with-sets-mechanic': 'ramp',

  // ── landfall ─────────────────────────────────────────────────────────────
  landfall: 'landfall',
  'lands-matter': 'landfall',
  'synergy-land': 'landfall',

  // ── mana sink ────────────────────────────────────────────────────────────
  'mana-dump': 'mana-sink',
  'mana-sink': 'mana-sink',
  'bottomless-mana-sink': 'mana-sink',
  'infinite-mana-sink': 'mana-sink',
  firebreathing: 'mana-sink',
  'shade-pump': 'mana-sink',

  // ── lifegain ─────────────────────────────────────────────────────────────
  'life-gain': 'lifegain',
  lifegain: 'lifegain',
  'repeatable-lifegain': 'lifegain',
  'lifegain-matters': 'lifegain',
  'synergy-lifegain': 'lifegain',
  'drain-life': 'lifegain',
  'life-drain': 'lifegain',
  'drain-creature': 'lifegain',

  // ── recursion ────────────────────────────────────────────────────────────
  recursion: 'recursion',
  'recursion-creature': 'recursion',
  reanimate: 'recursion',
  resurrect: 'recursion',
  zombify: 'recursion',
  'reanimate-cast': 'recursion',
  'reanimate-from-any': 'recursion',
  'reanimate-from-opponent': 'recursion',
  'reanimate-permanent': 'recursion',
  'reanimate-copy': 'recursion',
  'reanimate-land': 'recursion',
  'reanimate-artifact': 'recursion',
  recall: 'recursion',
  regrowth: 'recursion',
  'regrowth-creature': 'recursion',
  'regrowth-instant': 'recursion',
  'regrowth-sorcery': 'recursion',
  'regrowth-artifact': 'recursion',
  'regrowth-planeswalker': 'recursion',
  'regrowth-permanent': 'recursion',
  'regrowth-any': 'recursion',
  'regrowth-self': 'recursion',
  'self-recall': 'recursion',
  'self-regrowth': 'recursion',
  'recursion-self': 'recursion',
  'reanimate-self': 'recursion',
  'self-reanimate': 'recursion',
  'recursion-permanent': 'recursion',
  'recursion-enchantment': 'recursion',
  'recursion-instant': 'recursion',
  'recursion-sorcery': 'recursion',
  'recursion-artifact': 'recursion',
  'recursion-planeswalker': 'recursion',
  'recursion-any': 'recursion',
  'recursion-land': 'recursion',
  restock: 'recursion',
  'restock-self': 'recursion',
  'self-restock': 'recursion',
  'restock-to-top': 'recursion',
  rescue: 'recursion',
  'rescue-creature': 'recursion',
  'rescue-enchantment': 'recursion',
  'rescue-artifact': 'recursion',
  'rescue-land': 'recursion',
  'mass-reanimation': 'recursion',
  'castable-from-graveyard': 'recursion',
  flashback: 'recursion',
  'cast-from-graveyard': 'recursion',
  'activate-from-graveyard': 'recursion',
  'cheat-death': 'recursion',
  'cheat-death-self': 'recursion',
  'creature-reanimation-automatic': 'recursion',
  graveflicker: 'recursion',
  'temporary-reanimation': 'recursion',
  'trigger-from-graveyard': 'recursion',

  // ── graveyard matters ────────────────────────────────────────────────────
  'graveyard-fuel': 'graveyard-matters',
  'cards-in-graveyard-matter': 'graveyard-matters',
  'graveyard-fuel-creature': 'graveyard-matters',
  'graveyard-fuel-self': 'graveyard-matters',
  threshold: 'graveyard-matters',
  hellbent: 'graveyard-matters',
  undergrowth: 'graveyard-matters',
  'card-types-in-graveyard-matter': 'graveyard-matters',
  'synergy-graveyard-cast': 'graveyard-matters',

  // ── looting ──────────────────────────────────────────────────────────────
  loot: 'looting',
  rummage: 'looting',
  'repeatable-loot': 'looting',
  'repeatable-rummage': 'looting',
  'discard-outlet': 'looting',
  discardoutlet: 'looting',
  'discard-outlet-land': 'looting',
  'discard-exile': 'looting',
  'discard-to-exile': 'looting',

  // ── mill ─────────────────────────────────────────────────────────────────
  mill: 'mill',
  'mill-opponent': 'mill',
  'mill-any': 'mill',
  'mill-each': 'mill',
  'mill-exile': 'mill',
  'mill-self': 'mill',
  'self-mill': 'mill',
  'deck-destruction': 'mill',
  'synergy-mill': 'mill',

  // ── counterspells ────────────────────────────────────────────────────────
  counterspell: 'counterspells',
  'counterspell-soft': 'counterspells',
  'soft-counter': 'counterspells',
  'counterspell-reusable': 'counterspells',
  'counterspell-ability': 'counterspells',
  'counterspell-creature': 'counterspells',
  'counterspell-with-set-mechanic': 'counterspells',
  'counterspell-with-sets-mechanic': 'counterspells',

  // ── +1/+1 counters ───────────────────────────────────────────────────────
  'counters-matter': '+1/+1-counters',
  'gives-1-1-counters-to-all': '+1/+1-counters',
  'gives-counters-to-all': '+1/+1-counters',
  'counter-increaser': '+1/+1-counters',
  'counter-doubler': '+1/+1-counters',
  'counter-movement': '+1/+1-counters',
  'move-counters': '+1/+1-counters',
  'ability-counter': '+1/+1-counters',
  'keyword-counter': '+1/+1-counters',
  'remove-counters': '+1/+1-counters',
  'remove-counters-you': '+1/+1-counters',

  // ── blink-flicker ────────────────────────────────────────────────────────
  blink: 'blink-flicker',
  flicker: 'blink-flicker',
  'flicker-creature': 'blink-flicker',
  'flicker-slow': 'blink-flicker',
  'blink-slow': 'blink-flicker',
  'etb-other-creature': 'blink-flicker',

  // ── copy ─────────────────────────────────────────────────────────────────
  copy: 'copy',
  'copy-creature': 'copy',
  'copy-self': 'copy',
  'copy-spell': 'copy',
  'copy-instant': 'copy',
  'copy-sorcery': 'copy',
  'copy-artifact': 'copy',
  'copy-from-graveyard': 'copy',
  clone: 'copy',

  // ── tutor ────────────────────────────────────────────────────────────────
  tutor: 'tutor',
  'tutor-to': 'tutor',
  'tutor-hand': 'tutor',
  'tutor-to-hand': 'tutor',
  'tutor-battlefield': 'tutor',
  'tutor-onto-battlefield': 'tutor',
  'tutor-to-battlefield': 'tutor',
  'tutor-creature': 'tutor',
  'tutor-artifact': 'tutor',
  'tutor-any': 'tutor',
  'tutor-card': 'tutor',
  'tutor-mv': 'tutor',
  'tutor-cmc': 'tutor',
  'tutor-seek': 'tutor',
  'tutor-to-top': 'tutor',
  'tutor-totop': 'tutor',
  'demonic-tutor': 'tutor',
  consult: 'tutor',
  'consult-cast': 'tutor',
  'consult-onto-battlefield': 'tutor',
  seek: 'tutor',
  'seek-to-hand': 'tutor',
  wish: 'tutor',

  // ── cheat mana ───────────────────────────────────────────────────────────
  'cheat-mana': 'cheat-mana',
  'cost-ignorer': 'cheat-mana',
  'free-casting': 'cheat-mana',
  'cheat-into-play': 'cheat-mana',
  sneak: 'cheat-mana',
  'sneak-creature': 'cheat-mana',
  'sneak-from-library': 'cheat-mana',
  'sneak-self': 'cheat-mana',
  'sneak-land': 'cheat-mana',
  'cast-from-library': 'cheat-mana',
  'gives-castable-from-library': 'cheat-mana',
  'cast-from-top': 'cheat-mana',
  'play-from-top': 'cheat-mana',
  'cost-reducer': 'cheat-mana',
  convoke: 'cheat-mana',
  affinity: 'cheat-mana',
  'potentially-free': 'cheat-mana',
  'phyrexian-mana': 'cheat-mana',
  'free-cast-another': 'cheat-mana',
  'alternate-cost-tap-creature': 'cheat-mana',
  'discount-tap-creature': 'cheat-mana',
  'alternate-cost-sacrifice': 'cheat-mana',
  delve: 'cheat-mana',
  escape: 'cheat-mana',
  cascade: 'cheat-mana',

  // ── hand disruption ──────────────────────────────────────────────────────
  'hand-disruption': 'hand-disruption',
  coercion: 'hand-disruption',
  duress: 'hand-disruption',
  thoughtseize: 'hand-disruption',

  // ── library manipulation ────────────────────────────────────────────────
  'library-manipulation': 'library-manipulation',
  'top-deck-manipulation': 'library-manipulation',
  'bottom-deck-manipulation': 'library-manipulation',
  scry: 'library-manipulation',
  surveil: 'library-manipulation',
  'peek-library': 'library-manipulation',
  'spy-library': 'library-manipulation',
  'impulse-to-zone': 'library-manipulation',
  'impulse-onto-battlefield': 'library-manipulation',
  'impulse-artifact': 'library-manipulation',
  'impulse-land': 'library-manipulation',
  'impulse-creature': 'library-manipulation',

  // ── bounce ───────────────────────────────────────────────────────────────
  bounce: 'bounce',
  'bounce-self': 'bounce',
  'man-o-war': 'bounce',
  tuck: 'bounce',
  'tuck-self': 'bounce',

  // ── sweeper ──────────────────────────────────────────────────────────────
  boardwipe: 'sweeper',
  'mass-removal': 'sweeper',
  sweeper: 'sweeper',
  wipe: 'sweeper',
  'wrath-of-god': 'sweeper',
  'sweeper-one-sided': 'sweeper',
  'sweeper-graveyard': 'sweeper',

  // ── protection ───────────────────────────────────────────────────────────
  'protects-creature': 'protection',
  'combat-trick': 'protection',
  'damage-prevention': 'protection',
  'prevent-damage': 'protection',
  'damage-prevention-creature': 'protection',
  'damage-prevention-you': 'protection',
  'damage-prevention-self': 'protection',
  fog: 'protection',
  'fog-limited': 'protection',
  'fog-selective': 'protection',
  'pseudo-fog': 'protection',
  'regenerates-self': 'protection',
  'regenerates-other': 'protection',
  'gives-protection': 'protection',
  'protects-artifact': 'protection',
  'protects-planeswalker': 'protection',
  'protects-land': 'protection',
  freeze: 'protection',
  stun: 'protection',
  'freeze-creature': 'protection',
  'stun-creature': 'protection',
  lockdown: 'protection',
  'lockdown-creature': 'protection',

  // ── theft ────────────────────────────────────────────────────────────────
  theft: 'theft',
  'theft-creature': 'theft',
  'theft-cast': 'theft',
  'theft-artifact': 'theft',
  'theft-threaten': 'theft',
  threaten: 'theft',
  'control-changing-effects': 'theft',
  donate: 'theft',
  defector: 'theft',

  // ── token generation ─────────────────────────────────────────────────────
  'repeatable-token-generator': 'token-generation',
  'repeatable-creature-tokens': 'token-generation',
  'multiple-bodies': 'token-generation',
  'token-versions-of-cards': 'token-generation',
  'repeatable-artifact-tokens': 'token-generation',
  'out-of-color-token': 'token-generation',
  'temporary-token': 'token-generation',
  'copy-token': 'token-generation',
  'named-token': 'token-generation',
  'donate-token': 'token-generation',
  'splits-on-death': 'token-generation',
  'doomed-traveler': 'token-generation',
  'leaves-body-behind': 'token-generation',
  'repeatable-noncreature-tokens': 'token-generation',
  'synergy-token': 'tokens-matter',
  'synergy-token-creature': 'tokens-matter',

  // ── sacrifice ────────────────────────────────────────────────────────────
  'sac-outlet': 'sacrifice',
  'sacrifice-outlet': 'sacrifice',
  'sacrifice-outlet-creature': 'sacrifice',
  'sacrifice-outlet-artifact': 'sacrifice',
  'sacrifice-outlet-enchantment': 'sacrifice',
  'sacrifice-outlet-land': 'sacrifice',
  'sacrifice-outlet-permanent': 'sacrifice',
  'free-sac-outlet': 'sacrifice',
  'free-sacrifice-outlet': 'sacrifice',
  'repeatable-sacrifice-outlet': 'sacrifice',
  'death-trigger': 'sacrifice',
  deathtrigger: 'sacrifice',
  'death-trigger-self': 'sacrifice',
  morbid: 'sacrifice',
  'synergy-sacrifice': 'sacrifice',
  martyr: 'sacrifice',
  egg: 'sacrifice',

  // ── attack triggers ──────────────────────────────────────────────────────
  'attack-trigger': 'attack-triggers',
  'attacking-matters-self': 'attack-triggers',
  'attacking-matters': 'attack-triggers',
  'block-trigger': 'attack-triggers',
  'titan-trigger': 'attack-triggers',
  ninjutsu: 'attack-triggers',
  mentor: 'attack-triggers',

  // ── hate ─────────────────────────────────────────────────────────────────
  hate: 'hate',
  'hate-artifact': 'hate',
  'hate-blocker': 'hate',
  'hate-attacker': 'hate',
  'hate-discard': 'hate',
  'hate-counterspell': 'hate',
  'hate-draw': 'hate',
  'draw-hate': 'hate',
  'hate-enchantment': 'hate',
  'hate-nonbasic-land': 'hate',
  'hate-planeswalker': 'hate',
  'hate-flying': 'hate',
  'flying-hate': 'hate',
  'hate-tapped': 'hate',
  'hate-instant': 'hate',
  'hate-sorcery': 'hate',
  'hate-target': 'hate',
  'hate-high-pt': 'hate',
  'hate-low-power': 'hate',
  'hate-full-hand': 'hate',
  'hate-regenerate': 'hate',
  'hate-regeneration': 'hate',
  'prevent-regeneration': 'hate',
  'stops-regeneration': 'hate',
  'hate-white': 'hate',
  'white-hate': 'hate',
  'hate-black': 'hate',
  'black-hate': 'hate',
  'hate-red': 'hate',
  'red-hate': 'hate',
  'hate-green': 'hate',
  'green-hate': 'hate',
  'hate-blue': 'hate',
  'blue-hate': 'hate',
  hatebear: 'hate',
  'hate-color': 'hate',
  'hate-color-choose': 'hate',
  'color-hate': 'hate',

  // ── land matters ─────────────────────────────────────────────────────────
  'utility-land': 'land-matters',
  fetchland: 'land-matters',
  creatureland: 'land-matters',
  'man-land': 'land-matters',
  manland: 'land-matters',
  'land-removal': 'land-matters',
  'land-sacrifice': 'land-matters',
  'land-conversion': 'land-matters',
  'mass-land-denial': 'land-matters',
  'animate-land': 'land-matters',
  'untap-land': 'land-matters',
  'untapper-land': 'land-matters',

  // ── artifact synergy ─────────────────────────────────────────────────────
  'synergy-artifact': 'artifact-synergy',
  'synergy-artifact-creature': 'artifact-synergy',
  artifactfall: 'artifact-synergy',
  'becomes-artifact': 'artifact-synergy',
  artifactify: 'artifact-synergy',
  'tap-fuel-artifact': 'artifact-synergy',
  'untapper-artifact': 'artifact-synergy',
  'living-weapon': 'artifact-synergy',
  'synergy-equipment': 'artifact-synergy',
  'animate-artifact': 'artifact-synergy',
  'auto-equip': 'artifact-synergy',
  'quick-attach': 'artifact-synergy',
  'quick-equip': 'artifact-synergy',
  'snap-on': 'artifact-synergy',
  'etb-self-attach': 'artifact-synergy',

  // ── enchantment synergy ──────────────────────────────────────────────────
  'synergy-enchantment': 'enchantment-synergy',
  enchantmentfall: 'enchantment-synergy',
  constellation: 'enchantment-synergy',
  enchantress: 'enchantment-synergy',
  'synergy-aura': 'enchantment-synergy',
  'synergy-saga': 'enchantment-synergy',

  // ── spells matter ────────────────────────────────────────────────────────
  'synergy-instant': 'spells-matter',
  'synergy-sorcery': 'spells-matter',
  'synergy-noncreature': 'spells-matter',
  'second-spell-matters': 'spells-matter',
  heroic: 'spells-matter',
  strive: 'spells-matter',
  'cast-trigger': 'spells-matter',
  'cast-trigger-you': 'spells-matter',
  'cast-trigger-other': 'spells-matter',
  'cast-trigger-self': 'spells-matter',

  // ── cast from exile ──────────────────────────────────────────────────────
  'cast-from-exile': 'cast-from-exile',
  'gives-castable-from-exile': 'cast-from-exile',
  'castable-from-exile': 'cast-from-exile',

  // ── graveyard hate ───────────────────────────────────────────────────────
  'graveyard-to-library': 'graveyard-hate',
  'graveyard-hate': 'graveyard-hate',
  'hate-graveyard': 'graveyard-hate',

  // ── cycling ──────────────────────────────────────────────────────────────
  'cycling-non-mana': 'cycling',
  'gives-cycling': 'cycling',
  'pseudo-cycling': 'cycling',
  recycling: 'cycling',
  'synergy-cycling': 'cycling',
  'hate-cycling': 'cycling',

  // ── etb value ────────────────────────────────────────────────────────────
  'enters-and-leaves-trigger-self': 'etb-value',
  'enters-in-company': 'etb-value',
  'etb-untapper': 'etb-value',

  // ── aristocrats ──────────────────────────────────────────────────────────
  'blood-artist-ability': 'aristocrats',

  // ── proliferate ──────────────────────────────────────────────────────────
  'synergy-proliferate': 'proliferate',
  'virtual-proliferate': 'proliferate',

  // ── haste ────────────────────────────────────────────────────────────────
  'gives-haste': 'haste',
  'gains-haste': 'haste',
  'gives-super-haste': 'haste',
  'pseudo-haste': 'haste',
  'synergy-haste': 'haste',

  // ── flash ────────────────────────────────────────────────────────────────
  'gives-flash': 'flash',
  'gains-flash': 'flash',
  'synergy-flash': 'flash',

  // ── stax ─────────────────────────────────────────────────────────────────
  tax: 'stax',
  'cast-tax': 'stax',
  'tax-attack': 'stax',
  'tax-block': 'stax',
  'rule-of-law': 'stax',
  punisher: 'stax',

  // ── madness ──────────────────────────────────────────────────────────────
  madness: 'discard-matters',
  'gives-madness': 'discard-matters',
  'synergy-madness': 'discard-matters',
  'discard-matters': 'discard-matters',
  'self-discard-matters': 'discard-matters',
  'opponent-discard-matters': 'discard-matters',

  // ── storm ────────────────────────────────────────────────────────────────
  'storm-count-matters': 'storm',
  'storm-like': 'storm',
  'gives-storm': 'storm',

  // ── wheels ───────────────────────────────────────────────────────────────
  wheel: 'wheel',
  'wheel-one-sided': 'wheel',
  'wheel-symmetrical': 'wheel',
  'wheel-symmetrical-optional': 'wheel',
  miniwheel: 'wheel',

  // ── untap combo ──────────────────────────────────────────────────────────
  untapper: 'untap',
  'untapper-creature': 'untap',
  'untap-creature': 'untap',
  'extra-untap': 'untap',
  'ritual-untap': 'untap',

  // ── planeswalker support ─────────────────────────────────────────────────
  'planeswalker-support': 'planeswalker-support',
  'synergy-planeswalker': 'planeswalker-support',

  // ── energy ───────────────────────────────────────────────────────────────
  'energy-generator': 'energy',
  'counter-fuel-energy': 'energy',

  // ── legendary matters ────────────────────────────────────────────────────
  'synergy-legendary': 'legendary-matters',

  // ── food / treasure / clue ───────────────────────────────────────────────
  'repeatable-food': 'food',
  'synergy-food': 'food',
  'repeatable-treasures': 'treasure',
  'synergy-treasure': 'treasure',
  'repeatable-clues': 'clues',

  // ── colorless matters ────────────────────────────────────────────────────
  'synergy-colorless': 'colorless-matters',
  'colourless-matters': 'colorless-matters',

  // ── snow matters ─────────────────────────────────────────────────────────
  'synergy-snow': 'snow-matters',

  // ── multicolor matters ───────────────────────────────────────────────────
  'synergy-multicolor': 'multicolor-matters',
  'synergy-color-multi': 'multicolor-matters',
  'synergy-color-each': 'multicolor-matters',
  'synergy-color-share': 'multicolor-matters',

  // ── historic ─────────────────────────────────────────────────────────────
  'synergy-historic': 'historic',

  // ── color matters ────────────────────────────────────────────────────────
  'color-spent-matters': 'color-matters',
  'mana-spent-matters': 'color-matters',
  'offcolor-ability': 'color-matters',
  'color-change': 'color-matters',
  'color-change-self': 'color-matters',

  // ── extra turns ──────────────────────────────────────────────────────────
  'extra-turn': 'extra-turns',
  'extra-turn-each': 'extra-turns',
  'extra-turn-conditional': 'extra-turns',
  'time-walk': 'extra-turns',

  // ── monarch ──────────────────────────────────────────────────────────────
  monarch: 'monarch',
  'becomes-monarch': 'monarch',
  'monarch-support': 'monarch',

  // ── dredge ───────────────────────────────────────────────────────────────
  dredge: 'dredge',
  'dredge-like': 'dredge',

  // ── revolt ───────────────────────────────────────────────────────────────
  revolt: 'revolt',
  'synergy-revolt': 'revolt',

  // ── initiative ───────────────────────────────────────────────────────────
  initiative: 'initiative',
  'takes-initiative': 'initiative',
  venture: 'initiative',
  'venture-into-dungeon': 'initiative',

  // ── infect / -1/-1 counters ──────────────────────────────────────────────
  infect: 'infect',
  toxic: 'infect',
  poisonous: 'infect',
  'poison-counter': 'infect',
  'synergy-poison': 'infect',
  'synergy-infect': 'infect',
  'synergy-minus-counter': '-1/-1-counters',
  wither: '-1/-1-counters',
  'minus-counter': '-1/-1-counters',
  'minus-1-minus-1-counter': '-1/-1-counters',
};
