/* eslint-disable */
import { CardDetails, SUPPORTED_FORMATS } from '@utils/datatypes/Card';

// Placeholder used while real card details are being fetched from the cache
// (utils/cardDetailsCache). Mirrors the server-side getPlaceholderCard so
// downstream components that assume `card.details` is populated keep working
// during the hydration delay.
export const getPlaceholderCardDetails = (scryfall_id: string): CardDetails => ({
  scryfall_id,
  oracle_id: '',
  released_at: '',
  isToken: false,
  finishes: [],
  set: '',
  setIndex: -1,
  collector_number: '',
  promo: false,
  reprint: false,
  digital: false,
  full_name: '',
  name: '',
  name_lower: '',
  artist: '',
  scryfall_uri: '',
  rarity: '',
  legalities: Object.fromEntries(SUPPORTED_FORMATS.map((format) => [format, 'not_legal' as const])),
  oracle_text: '',
  image_normal: '/content/loadingcard.png',
  cmc: 0,
  type: '',
  colors: [],
  color_identity: [],
  parsed_cost: [],
  colorcategory: 'Colorless',
  border_color: 'black',
  language: 'en',
  mtgo_id: 0,
  layout: '',
  tcgplayer_id: '',
  power: '',
  toughness: '',
  loyalty: '',
  error: false,
  full_art: false,
  prices: {},
  tokens: [],
  set_name: '',
  produced_mana: [],
  keywords: [],
  games: [],
  gamesEverAvailable: [],
  reserved: false,
});
