node jobs/draftAnalytics/calculate_scarcity.js
node jobs/draftAnalytics/calculate_pass_percent.js
node jobs/draftAnalytics/calculate_pick_position.js
node jobs/draftAnalytics/calculate_played_first_pick.js
node jobs/draftAnalytics/calculate_mainboard_percent.js
node jobs/draftAnalytics/calculate_flexibility.js
