# Paths are relative to this file
services:
  node:
    container_name: cube
    image: node:22.12.0
    volumes:
      - ../../../:/home/node/app
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=8192
    env_file:
      - ../../server/.env_EXAMPLE
      - path: ../../server/.env
        required: false
    ports:
      # browser entry point
      - 8080:5000
      # Node
      - 5001:5000
    expose:
      - '8080'
      - '5001'
    # Relative to root directory
    command: ./packages/scripts/src/docker/run.sh
    entrypoint: ['/bin/sh']
    init: true
    networks:
      - cubecobra
  recommender:
    container_name: recommender
    image: node:22.12.0
    volumes:
      - ../../../:/home/node/app
    user: 'node'
    working_dir: /home/node/app/packages/recommenderService
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=8192
    env_file:
      - path: ../../recommenderService/.env
        required: false
    command: ['npm', 'run', 'dev']
    init: true
    networks:
      - cubecobra
    depends_on:
      - node

networks:
  # Rename. by default network is prefixed by folder name
  cubecobra:
    driver: bridge
    name: 'cubecobra'
