module.exports = {
  tags:[String],
  finish:String,
  colors:[String],
  status:String,
  cmc:Number,
  cardID:String,
  type_line:String,
  details: {
    color_identity: [String],
    set: String,
    collector_number:String,
    promo:Boolean,
    digital:Boolean,
    isToken:Boolean,
    border_color:String,
    name:String,
    name_lower:String,
    full_name: String,
    artist:String,
    scryfall_uri:String,
    rarity:String,
    oracle_text:String,
    _id:String,
    oracle_id:String,
    cmc:Number,
    legalities:{
      Legacy:Boolean,
      Modern:Boolean,
      Standard:Boolean,
      Pioneer:Boolean,
      Pauper:Boolean
    },
    parsed_cost:[String],
    colors:[String],
    type:String,
    full_art:Boolean,
    language:String,
    tcgplayer_id:Number,
    image_small:String,
    image_normal:String,
    art_crop:String,
    colorcategory:String
  }
}